name: 'first exercise'
on:
  push:
jobs:
  get-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v3
        with:
          node-version: '24.18.0'
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - run: npm ci
      - if: always()
        run: |
          echo "Test completed"
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"